# Wave Simulation Configuration

[parameters]
# Wave physical properties
k_p = 3.95            # Peak wave number
k_w = 0.03            # Wave number bandwidth (relative to k_p or absolute)
k_w_relative = true  # If true, k_w = k_w * k_p
Hs = 0.2             # Significant wave height
kph = 0.79            # kph parameter
t0 = 0                # Initial time

# Wave number range configuration
kmin_factor = 4.0      # kmin = k_p - kmin_factor*k_w (unless < 0, then 0.1*k_p)
kmax_factor = 4.0      # kmax = k_p + kmax_factor*k_w
custom_kmin = -1.0     # If > 0, use this exact value for kmin instead of factor
custom_kmax = -1.0     # If > 0, use this exact value for kmax instead of factor

# Spectrum configuration
spectrum_type = "gaussian"  # Options: "gaussian", "jonswap", "custom"

# JONSWAP specific parameters (used only when spectrum_type = "jonswap")
gamma = 3.3                # Peak enhancement factor
sigma_a = 0.07             # Left spectral width
sigma_b = 0.09             # Right spectral width

# Custom spectrum (used only when spectrum_type = "custom")
spectrum_file = "custom_spectrum.csv"  # Path to custom spectrum file

# Simulation parameters
Ntp = 128            # Number of points in a period
Nperiod = 2400       # Time scale for periods
Nxperiod = 60        # Number of periods in space
ppp = 32             # Points per wavelength
Nk = 128             # Number of wave components
water_type = "finitewater"  # "deepwater" or "finitewater"

[simulation]
# Simulation control
N_test = 14           # Number of simulations to run
seed_max = 500        # Maximum seed number to sample from
use_parallel = true   # Whether to use parallel processing
num_workers = 0       # Number of worker processes (0 = auto-detect)

[output]
# Output configuration
filename = "wave_batch_results_gaussian_shallow_highHs.jld2"  # Output filename
directory = "results_gaussian_shallow_highHs"                 # Output directory for plots

[plot]
# Plot configuration
size = [800, 600]    # Default plot size [width, height]
dpi = 300            # Plot resolution
